name: rest-app-cs-template
description: base plugin to develop a full-featured API using C#, .NET and REST, running on a container cluster
types:
  - app-template
inputs:
  - label: Project name
    type: text
    name: project_name
    global: true
    default: project-name